-- ============================================================
-- TABLA: TOPOGRAFÍA ICD-O 3.1 (Completa y Validada)
-- Fuente: Lista Numérica (Tabular) - CIE-O-3.1
-- Rango: C00.0 - C80.9
-- ============================================================

DROP TABLE IF EXISTS cieo_3_1_topografia;

CREATE TABLE cieo_3_1_topografia (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    UNIQUE KEY uq_topografia_codigo (codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
-- INSERTS MASIVOS
-- ============================================================

INSERT INTO cieo_3_1_topografia (codigo, descripcion) VALUES
-- C00-C14: LABIO, CAVIDAD ORAL Y FARINGE
('C00.0', 'Labio superior, parte externa'),
('C00.1', 'Labio inferior, parte externa'),
('C00.2', 'Labio, parte externa, SAI'),
('C00.3', 'Mucosa del labio superior'),
('C00.4', 'Mucosa del labio inferior'),
('C00.5', 'Mucosa del labio, SAI'),
('C00.6', 'Comisura del labio'),
('C00.8', 'Lesión de localizaciones contiguas del labio'),
('C00.9', 'Labio, SAI'),
('C01.9', 'Base de la lengua, SAI'),
('C02.0', 'Superficie dorsal de la lengua, SAI'),
('C02.1', 'Borde de la lengua'),
('C02.2', 'Superficie ventral de la lengua, SAI'),
('C02.3', 'Dos tercios anteriores de la lengua, SAI'),
('C02.4', 'Amígdala lingual'),
('C02.8', 'Lesión de localizaciones contiguas de la lengua'),
('C02.9', 'Lengua, SAI'),
('C03.0', 'Encía superior'),
('C03.1', 'Encía inferior'),
('C03.9', 'Encía, SAI'),
('C04.0', 'Parte anterior del suelo de la boca'),
('C04.1', 'Parte lateral del suelo de la boca'),
('C04.8', 'Lesión de localizaciones contiguas del suelo de la boca'),
('C04.9', 'Suelo de la boca, SAI'),
('C05.0', 'Paladar duro'),
('C05.1', 'Paladar blando, SAI'),
('C05.2', 'Úvula'),
('C05.8', 'Lesión de localizaciones contiguas del paladar'),
('C05.9', 'Paladar, SAI'),
('C06.0', 'Mucosa de la mejilla'),
('C06.1', 'Vestíbulo de la boca'),
('C06.2', 'Área retromolar'),
('C06.8', 'Lesión de localizaciones contiguas de otras partes y de las no especificadas de la boca'),
('C06.9', 'Boca, SAI'),
('C07.9', 'Glándula parótida'),
('C08.0', 'Glándula submandibular'),
('C08.1', 'Glándula sublingual'),
('C08.8', 'Lesión de localizaciones contiguas de las glándulas salivales mayores'),
('C08.9', 'Glándula salival mayor, SAI'),
('C09.0', 'Fosa amigdalina'),
('C09.1', 'Pilar amigdalino'),
('C09.8', 'Lesión de localizaciones contiguas de la amígdala'),
('C09.9', 'Amígdala, SAI'),
('C10.0', 'Valécula'),
('C10.1', 'Cara anterior de la epiglotis'),
('C10.2', 'Pared lateral de la orofaringe'),
('C10.3', 'Pared posterior de la orofaringe'),
('C10.4', 'Hendidura branquial'),
('C10.8', 'Lesión de localizaciones contiguas de la orofaringe'),
('C10.9', 'Orofaringe, SAI'),
('C11.0', 'Pared superior de la nasofaringe'),
('C11.1', 'Pared posterior de la nasofaringe'),
('C11.2', 'Pared lateral de la nasofaringe'),
('C11.3', 'Pared anterior de la nasofaringe'),
('C11.8', 'Lesión de localizaciones contiguas de la nasofaringe'),
('C11.9', 'Nasofaringe, SAI'),
('C12.9', 'Seno piriforme'),
('C13.0', 'Región postcricoidea'),
('C13.1', 'Pliegue aritenoepiglótico, cara hipofaríngea'),
('C13.2', 'Pared posterior de la hipofaringe'),
('C13.8', 'Lesión de localizaciones contiguas de la hipofaringe'),
('C13.9', 'Hipofaringe, SAI'),
('C14.0', 'Faringe, SAI'),
('C14.2', 'Anillo de Waldeyer'),
('C14.8', 'Lesión de localizaciones contiguas del labio, de la cavidad oral y de la faringe'),

-- C15-C26: ÓRGANOS DIGESTIVOS
('C15.0', 'Esófago cervical'),
('C15.1', 'Esófago torácico'),
('C15.2', 'Esófago abdominal'),
('C15.3', 'Tercio superior del esófago'),
('C15.4', 'Tercio medio del esófago'),
('C15.5', 'Tercio inferior del esófago'),
('C15.8', 'Lesión de localizaciones contiguas del esófago'),
('C15.9', 'Esófago, SAI'),
('C16.0', 'Cardias, SAI'),
('C16.1', 'Fondo gástrico'),
('C16.2', 'Cuerpo gástrico'),
('C16.3', 'Antro gástrico'),
('C16.4', 'Píloro'),
('C16.5', 'Curvatura menor del estómago, SAI'),
('C16.6', 'Curvatura mayor del estómago, SAI'),
('C16.8', 'Lesión de localizaciones contiguas del estómago'),
('C16.9', 'Estómago, SAI'),
('C17.0', 'Duodeno'),
('C17.1', 'Yeyuno'),
('C17.2', 'Íleon'),
('C17.3', 'Divertículo de Meckel'),
('C17.8', 'Lesión de localizaciones contiguas del intestino delgado'),
('C17.9', 'Intestino delgado, SAI'),
('C18.0', 'Ciego'),
('C18.1', 'Apéndice'),
('C18.2', 'Colon ascendente'),
('C18.3', 'Ángulo hepático'),
('C18.4', 'Colon transverso'),
('C18.5', 'Ángulo esplénico'),
('C18.6', 'Colon descendente'),
('C18.7', 'Colon sigmoide'),
('C18.8', 'Lesión de localizaciones contiguas del colon'),
('C18.9', 'Colon, SAI'),
('C19.9', 'Unión rectosigmoidea'),
('C20.9', 'Recto, SAI'),
('C21.0', 'Ano, SAI'),
('C21.1', 'Conducto anal'),
('C21.2', 'Zona cloacogénica'),
('C21.8', 'Lesión de localizaciones contiguas del recto, del ano y del conducto anal'),
('C22.0', 'Hígado'),
('C22.1', 'Vías biliares intrahepáticas'),
('C23.9', 'Vesícula biliar'),
('C24.0', 'Vías biliares extrahepáticas'),
('C24.1', 'Ampolla de Vater'),
('C24.8', 'Lesión de localizaciones contiguas de las vías biliares'),
('C24.9', 'Vías biliares, SAI'),
('C25.0', 'Cabeza del páncreas'),
('C25.1', 'Cuerpo del páncreas'),
('C25.2', 'Cola del páncreas'),
('C25.3', 'Conducto pancreático'),
('C25.4', 'Islotes de Langerhans'),
('C25.7', 'Otras partes especificadas del páncreas'),
('C25.8', 'Lesión de localizaciones contiguas del páncreas'),
('C25.9', 'Páncreas, SAI'),
('C26.0', 'Tracto intestinal, SAI'),
('C26.8', 'Lesión de localizaciones contiguas de los órganos digestivos'),
('C26.9', 'Aparato digestivo, SAI'),

-- C30-C39: APARATO RESPIRATORIO Y ÓRGANOS INTRATORÁCICOS
('C30.0', 'Fosa nasal'),
('C30.1', 'Oído medio'),
('C31.0', 'Seno maxilar'),
('C31.1', 'Seno etmoidal'),
('C31.2', 'Seno frontal'),
('C31.3', 'Seno esfenoidal'),
('C31.8', 'Lesión de localizaciones contiguas de los senos accesorios'),
('C31.9', 'Seno accesorio, SAI'),
('C32.0', 'Glotis'),
('C32.1', 'Región supraglótica'),
('C32.2', 'Región subglótica'),
('C32.3', 'Cartílago laríngeo'),
('C32.8', 'Lesión de localizaciones contiguas de la laringe'),
('C32.9', 'Laringe, SAI'),
('C33.9', 'Tráquea'),
('C34.0', 'Bronquio principal'),
('C34.1', 'Lóbulo superior, pulmón'),
('C34.2', 'Lóbulo medio, pulmón'),
('C34.3', 'Lóbulo inferior, pulmón'),
('C34.8', 'Lesión de localizaciones contiguas del bronquio y del pulmón'),
('C34.9', 'Bronquio o pulmón, SAI'),
('C37.9', 'Timo'),
('C38.0', 'Corazón'),
('C38.1', 'Mediastino anterior'),
('C38.2', 'Mediastino posterior'),
('C38.3', 'Mediastino, SAI'),
('C38.4', 'Pleura, SAI'),
('C38.8', 'Lesión de localizaciones contiguas del corazón, del mediastino y de la pleura'),
('C39.0', 'Vías respiratorias superiores, SAI'),
('C39.8', 'Lesión de localizaciones contiguas de los órganos respiratorios e intratorácicos'),
('C39.9', 'Sitios mal definidos del aparato respiratorio'),

-- C40-C41: HUESOS, ARTICULACIONES Y CARTÍLAGOS
('C40.0', 'Huesos largos del miembro superior, escápula y articulaciones asociadas'),
('C40.1', 'Huesos cortos del miembro superior y articulaciones asociadas'),
('C40.2', 'Huesos largos del miembro inferior y articulaciones asociadas'),
('C40.3', 'Huesos cortos del miembro inferior y articulaciones asociadas'),
('C40.8', 'Lesión de localizaciones contiguas de los huesos, de las articulaciones y de los cartílagos articulares de los miembros'),
('C40.9', 'Huesos de los miembros, SAI'),
('C41.0', 'Huesos del cráneo y de la cara y articulaciones asociadas'),
('C41.1', 'Mandíbula'),
('C41.2', 'Columna vertebral'),
('C41.3', 'Costilla, esternón, clavícula y articulaciones asociadas'),
('C41.4', 'Huesos de la pelvis, sacro, cóccix y articulaciones asociadas'),
('C41.8', 'Lesión de localizaciones contiguas de los huesos, de las articulaciones y de los cartílagos articulares'),
('C41.9', 'Hueso, SAI'),

-- C42: SISTEMAS HEMATOPOYÉTICO Y RETICULOENDOTELIAL (RESTAURADO)
('C42.0', 'Sangre'),
('C42.1', 'Médula ósea'),
('C42.2', 'Bazo'),
('C42.3', 'Sistema reticuloendotelial, SAI'),
('C42.4', 'Sistema hematopoyético, SAI'),

-- C44: PIEL
('C44.0', 'Piel del labio, SAI'),
('C44.1', 'Párpado'),
('C44.2', 'Oído externo'),
('C44.3', 'Piel de otras partes y de las no especificadas de la cara'),
('C44.4', 'Piel del cuero cabelludo y del cuello'),
('C44.5', 'Piel del tronco'),
('C44.6', 'Piel del miembro superior y del hombro'),
('C44.7', 'Piel del miembro inferior y de la cadera'),
('C44.8', 'Lesión de localizaciones contiguas de la piel'),
('C44.9', 'Piel, SAI'),

-- C47: NERVIOS PERIFÉRICOS Y SISTEMA NERVIOSO AUTÓNOMO
('C47.0', 'Nervios periféricos y sistema nervioso autónomo de la cabeza, de la cara y del cuello'),
('C47.1', 'Nervios periféricos y sistema nervioso autónomo del miembro superior y del hombro'),
('C47.2', 'Nervios periféricos y sistema nervioso autónomo del miembro inferior y de la cadera'),
('C47.3', 'Nervios periféricos y sistema nervioso autónomo del tórax'),
('C47.4', 'Nervios periféricos y sistema nervioso autónomo del abdomen'),
('C47.5', 'Nervios periféricos y sistema nervioso autónomo de la pelvis'),
('C47.6', 'Nervios periféricos y sistema nervioso autónomo del tronco, SAI'),
('C47.8', 'Lesión de localizaciones contiguas de los nervios periféricos y del sistema nervioso autónomo'),
('C47.9', 'Sistema nervioso autónomo, SAI'),

-- C48: TEJIDO RETROPERITONEAL Y PERITONEO
('C48.0', 'Retroperitoneo'),
('C48.1', 'Partes especificadas del peritoneo'),
('C48.2', 'Peritoneo, SAI'),
('C48.8', 'Lesión de localizaciones contiguas del tejido retroperitoneal y del peritoneo'),

-- C49: TEJIDO CONJUNTIVO, SUBCUTÁNEO Y DE OTROS TEJIDOS BLANDOS
('C49.0', 'Tejido conjuntivo, subcutáneo y otros tejidos blandos de la cabeza, de la cara y del cuello'),
('C49.1', 'Tejido conjuntivo, subcutáneo y otros tejidos blandos del miembro superior y del hombro'),
('C49.2', 'Tejido conjuntivo, subcutáneo y otros tejidos blandos del miembro inferior y de la cadera'),
('C49.3', 'Tejido conjuntivo, subcutáneo y otros tejidos blandos del tórax'),
('C49.4', 'Tejido conjuntivo, subcutáneo y otros tejidos blandos del abdomen'),
('C49.5', 'Tejido conjuntivo, subcutáneo y otros tejidos blandos de la pelvis'),
('C49.6', 'Tejido conjuntivo, subcutáneo y otros tejidos blandos del tronco, SAI'),
('C49.8', 'Lesión de localizaciones contiguas del tejido conjuntivo, subcutáneo y de otros tejidos blandos'),
('C49.9', 'Tejido conjuntivo, subcutáneo y otros tejidos blandos, SAI'),

-- C50: MAMA
('C50.0', 'Pezón'),
('C50.1', 'Porción central de la mama'),
('C50.2', 'Cuadrante superior interno de la mama'),
('C50.3', 'Cuadrante inferior interno de la mama'),
('C50.4', 'Cuadrante superior externo de la mama'),
('C50.5', 'Cuadrante inferior externo de la mama'),
('C50.6', 'Prolongación axilar de la mama'),
('C50.8', 'Lesión de localizaciones contiguas de la mama'),
('C50.9', 'Mama, SAI'),

-- C51-C58: ÓRGANOS GENITALES FEMENINOS
('C51.0', 'Labio mayor'),
('C51.1', 'Labio menor'),
('C51.2', 'Clítoris'),
('C51.8', 'Lesión de localizaciones contiguas de la vulva'),
('C51.9', 'Vulva, SAI'),
('C52.9', 'Vagina, SAI'),
('C53.0', 'Endocérvix'),
('C53.1', 'Exocérvix'),
('C53.8', 'Lesión de localizaciones contiguas del cuello del útero'),
('C53.9', 'Cuello del útero, SAI'),
('C54.0', 'Istmo uterino'),
('C54.1', 'Endometrio'),
('C54.2', 'Miometrio'),
('C54.3', 'Fondo del útero'),
('C54.8', 'Lesión de localizaciones contiguas del cuerpo del útero'),
('C54.9', 'Cuerpo del útero'),
('C55.9', 'Útero, SAI'),
('C56.9', 'Ovario'),
('C57.0', 'Trompa de Falopio'),
('C57.1', 'Ligamento ancho'),
('C57.2', 'Ligamento redondo'),
('C57.3', 'Parametrio'),
('C57.4', 'Anexos uterinos, SAI'),
('C57.7', 'Otras partes especificadas de los órganos genitales femeninos'),
('C57.8', 'Lesión de localizaciones contiguas de los órganos genitales femeninos'),
('C57.9', 'Órgano genital femenino, SAI'),
('C58.9', 'Placenta'),

-- C60-C63: ÓRGANOS GENITALES MASCULINOS
('C60.0', 'Prepucio'),
('C60.1', 'Glande'),
('C60.2', 'Cuerpo del pene'),
('C60.8', 'Lesión de localizaciones contiguas del pene'),
('C60.9', 'Pene, SAI'),
('C61.9', 'Próstata, SAI'),
('C62.0', 'Testículo no descendido'),
('C62.1', 'Testículo descendido'),
('C62.9', 'Testículo, SAI'),
('C63.0', 'Epidídimo'),
('C63.1', 'Cordón espermático'),
('C63.2', 'Escroto'),
('C63.7', 'Otras partes especificadas de los órganos genitales masculinos'),
('C63.8', 'Lesión de localizaciones contiguas de los órganos genitales masculinos'),
('C63.9', 'Órgano genital masculino, SAI'),

-- C64-C68: APARATO URINARIO
('C64.9', 'Riñón, SAI'),
('C65.9', 'Pelvis renal'),
('C66.9', 'Uréter'),
('C67.0', 'Trígono vesical'),
('C67.1', 'Cúpula vesical'),
('C67.2', 'Pared lateral de la vejiga'),
('C67.3', 'Pared anterior de la vejiga'),
('C67.4', 'Pared posterior de la vejiga'),
('C67.5', 'Cuello de la vejiga'),
('C67.6', 'Orificio ureteral'),
('C67.7', 'Uraco'),
('C67.8', 'Lesión de localizaciones contiguas de la vejiga'),
('C67.9', 'Vejiga urinaria, SAI'),
('C68.0', 'Uretra'),
('C68.1', 'Glándula parauretral'),
('C68.8', 'Lesión de localizaciones contiguas de los órganos urinarios'),
('C68.9', 'Órgano urinario, SAI'),

-- C69-C72: OJO, ENCÉFALO Y OTRAS PARTES DEL SISTEMA NERVIOSO CENTRAL
('C69.0', 'Conjuntiva'),
('C69.1', 'Córnea'),
('C69.2', 'Retina'),
('C69.3', 'Coroides'),
('C69.4', 'Cuerpo ciliar'),
('C69.5', 'Glándula lagrimal'),
('C69.6', 'Órbita, SAI'),
('C69.8', 'Lesión de localizaciones contiguas del ojo y sus anexos'),
('C69.9', 'Ojo, SAI'),
('C70.0', 'Meninges cerebrales'),
('C70.1', 'Meninges espinales'),
('C70.9', 'Meninges, SAI'),
('C71.0', 'Cerebro excepto lóbulos y ventrículos'),
('C71.1', 'Lóbulo frontal'),
('C71.2', 'Lóbulo temporal'),
('C71.3', 'Lóbulo parietal'),
('C71.4', 'Lóbulo occipital'),
('C71.5', 'Ventrículo cerebral'),
('C71.6', 'Cerebelo'),
('C71.7', 'Tronco del encéfalo'),
('C71.8', 'Lesión de localizaciones contiguas del encéfalo'),
('C71.9', 'Encéfalo, SAI'),
('C72.0', 'Médula espinal'),
('C72.1', 'Cola de caballo'),
('C72.2', 'Nervio olfatorio'),
('C72.3', 'Nervio óptico'),
('C72.4', 'Nervio acústico'),
('C72.5', 'Nervio craneal, SAI'),
('C72.8', 'Lesión de localizaciones contiguas del encéfalo y otras partes del sistema nervioso central'),
('C72.9', 'Sistema nervioso, SAI'),

-- C73-C75: TIROIDES Y OTRAS GLÁNDULAS ENDOCRINAS
('C73.9', 'Glándula tiroides'),
('C74.0', 'Corteza suprarrenal'),
('C74.1', 'Médula suprarrenal'),
('C74.9', 'Glándula suprarrenal, SAI'),
('C75.0', 'Glándula paratiroides'),
('C75.1', 'Glándula pituitaria (hipófisis)'),
('C75.2', 'Conducto craneofaríngeo'),
('C75.3', 'Glándula pineal'),
('C75.4', 'Cuerpo carotídeo'),
('C75.5', 'Cuerpo aórtico y otros paraganglios'),
('C75.8', 'Lesión de localizaciones contiguas de las glándulas endocrinas y de otras estructuras afines'),
('C75.9', 'Glándula endocrina, SAI'),

-- C76-C80: OTRAS LOCALIZACIONES Y MAL DEFINIDAS
('C76.0', 'Cabeza, cara y cuello'),
('C76.1', 'Tórax, SAI'),
('C76.2', 'Abdomen, SAI'),
('C76.3', 'Pelvis, SAI'),
('C76.4', 'Miembro superior, SAI'),
('C76.5', 'Miembro inferior, SAI'),
('C76.7', 'Otras localizaciones mal definidas'),
('C76.8', 'Lesión de localizaciones contiguas de sitios mal definidos'),
('C77.0', 'Ganglios linfáticos de la cabeza, de la cara y del cuello'),
('C77.1', 'Ganglios linfáticos intratorácicos'),
('C77.2', 'Ganglios linfáticos intraabdominales'),
('C77.3', 'Ganglios linfáticos de la axila y del miembro superior'),
('C77.4', 'Ganglios linfáticos de la región inguinal y del miembro inferior'),
('C77.5', 'Ganglios linfáticos de la pelvis'),
('C77.8', 'Ganglios linfáticos de regiones múltiples'),
('C77.9', 'Ganglio linfático, SAI'),
('C80.9', 'Sitio primario desconocido');